name: Test for dev branches

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "*"
      - "!master"
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - run: bash test.sh