name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - run: bash build-windows.sh

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: srtor
          path: build
